/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaomi_mimcdemo_av_FFmpegAudioEncoder */

#ifndef _Included_com_xiaomi_mimcdemo_av_FFmpegAudioEncoder
#define _Included_com_xiaomi_mimcdemo_av_FFmpegAudioEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaomi_mimcdemo_av_FFmpegAudioEncoder
 * Method:    startEncoder
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xiaomi_mimcdemo_av_FFmpegAudioEncoder_startEncoder
  (JNIEnv *, jobject);

/*
 * Class:     com_xiaomi_mimcdemo_av_FFmpegAudioEncoder
 * Method:    stopEncoder
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xiaomi_mimcdemo_av_FFmpegAudioEncoder_stopEncoder
  (JNIEnv *, jobject);

/*
 * Class:     com_xiaomi_mimcdemo_av_FFmpegAudioEncoder
 * Method:    encode
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_xiaomi_mimcdemo_av_FFmpegAudioEncoder_encode
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
