/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaomi_mimcdemo_av_FFmpegAudioDecoder */

#ifndef _Included_com_xiaomi_mimcdemo_av_FFmpegAudioDecoder
#define _Included_com_xiaomi_mimcdemo_av_FFmpegAudioDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaomi_mimcdemo_av_FFmpegAudioDecoder
 * Method:    startDecoder
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xiaomi_mimcdemo_av_FFmpegAudioDecoder_startDecoder
  (JNIEnv *, jobject);

/*
 * Class:     com_xiaomi_mimcdemo_av_FFmpegAudioDecoder
 * Method:    stopDecoder
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xiaomi_mimcdemo_av_FFmpegAudioDecoder_stopDecoder
  (JNIEnv *, jobject);

/*
 * Class:     com_xiaomi_mimcdemo_av_FFmpegAudioDecoder
 * Method:    decode
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_xiaomi_mimcdemo_av_FFmpegAudioDecoder_decode
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
